# Generated by Django 2.0.3 on 2018-06-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('batch', models.IntegerField(default=0)),
                ('gain', models.IntegerField(default=0)),
                ('sold_share', models.IntegerField(default=0)),
                ('sold_normal', models.IntegerField(default=0)),
                ('sold_vacant', models.IntegerField(default=0)),
                ('sold_500', models.IntegerField(default=0)),
                ('sold_700', models.IntegerField(default=0)),
                ('sold_800', models.IntegerField(default=0)),
                ('sold_900', models.IntegerField(default=0)),
                ('sold_1000', models.IntegerField(default=0)),
                ('sold_1200', models.IntegerField(default=0)),
                ('sold_1500', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.City')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('selected', models.BooleanField(default=False)),
                ('sold', models.CharField(default='Vacant', max_length=50)),
                ('user_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Row')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.City')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Sector'),
        ),
        migrations.AddField(
            model_name='row',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Sector'),
        ),
    ]
